---
common-steps:

  - &installdeps
    run:
      name: Install Debian packaging dependencies
      command: |
        apt-get update && apt-get install -y make sudo
        make install-deps

  - &installtestdeps
    run:
      name: Install test dependencies
      command: |
        apt-get install reprotest faketime -y --no-install-recommends
        .venv/bin/pip install -r test-requirements.txt


version: 2.1

jobs:
  lint-and-test:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - *installdeps
      - *installtestdeps
      - run:
          name: install test requirements, run linters, and run tests
          command: |
            source .venv/bin/activate
            sed -i -re "292s/^(\s+).*\$/\1return _.prepend_to_build_command_raw('')/" /usr/lib/python3/dist-packages/reprotest/build.py
            make test

  reprotest-wheels:
    docker:
      - image: debian:bullseye
    # Our "ci" user will have problems if the repository is in /root
    working_directory: "/srv"
    steps:
      - checkout
      - *installdeps
      - *installtestdeps
      - run:
          name: install test requirements and run tests
          command: |
            adduser --system ci --ingroup root
            sed -i -re "292s/^(\s+).*\$/\1return _.prepend_to_build_command_raw('')/" /usr/lib/python3/dist-packages/reprotest/build.py
            # Have our "ci" user take over the git repo
            chown ci:root -R .
            sudo -u ci bash -c "source .venv/bin/activate && pytest -vvs tests/test_reproducible_wheels.py"

workflows:
  builder_ci:
    jobs:
      - lint-and-test
      - reprotest-wheels

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - reprotest-wheels
